import io
from langchain_core.tools import tool
from core import storage


@tool
def create_word_document(filename: str, title: str, sections: list[dict]) -> str:
    """Create a Word (.docx) document.

    Args:
        filename: Output filename, e.g. 'report.docx'
        title: Document title shown at the top
        sections: List of section dicts, each with:
                  - "heading" (str): section heading
                  - "body" (str): paragraph text; prefix lines with '- ' for bullet points
    """
    try:
        from docx import Document
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()
        t = doc.add_heading(title, level=0)
        t.alignment = WD_ALIGN_PARAGRAPH.CENTER

        for section in sections:
            heading = section.get("heading", "")
            body = section.get("body", "")
            if heading:
                doc.add_heading(heading, level=1)
            for line in body.splitlines():
                line = line.strip()
                if not line:
                    continue
                if line.startswith("- ") or line.startswith("* "):
                    doc.add_paragraph(line[2:], style="List Bullet")
                else:
                    doc.add_paragraph(line)

        buf = io.BytesIO()
        doc.save(buf)
        location = storage.write_file(filename, buf.getvalue())
        return f"Word document saved: {location}"
    except Exception as e:
        return f"Error creating Word document: {e}"


@tool
def create_excel_spreadsheet(filename: str, sheets: list[dict]) -> str:
    """Create an Excel (.xlsx) spreadsheet.

    Args:
        filename: Output filename, e.g. 'report.xlsx'
        sheets: List of sheet dicts, each with:
                - "name" (str): sheet tab name
                - "headers" (list[str]): column headers
                - "rows" (list[list]): data rows, each a list of cell values
    """
    try:
        import openpyxl
        from openpyxl.styles import Font, PatternFill, Alignment

        wb = openpyxl.Workbook()

        for i, sheet in enumerate(sheets):
            ws = wb.active if i == 0 else wb.create_sheet()
            ws.title = sheet.get("name", f"Sheet{i+1}")
            headers = sheet.get("headers", [])
            rows = sheet.get("rows", [])

            for col, header in enumerate(headers, 1):
                cell = ws.cell(row=1, column=col, value=header)
                cell.font = Font(bold=True, color="FFFFFF")
                cell.fill = PatternFill("solid", fgColor="1F497D")
                cell.alignment = Alignment(horizontal="center")

            for row_idx, row in enumerate(rows, 2):
                for col_idx, value in enumerate(row, 1):
                    ws.cell(row=row_idx, column=col_idx, value=value)

            for col in ws.columns:
                max_len = max((len(str(c.value or "")) for c in col), default=8)
                ws.column_dimensions[col[0].column_letter].width = min(max_len + 4, 60)

        buf = io.BytesIO()
        wb.save(buf)
        location = storage.write_file(filename, buf.getvalue())
        return f"Excel spreadsheet saved: {location}"
    except Exception as e:
        return f"Error creating Excel spreadsheet: {e}"


@tool
def create_powerpoint(filename: str, title: str, slides: list[dict]) -> str:
    """Create a PowerPoint (.pptx) presentation.

    Args:
        filename: Output filename, e.g. 'presentation.pptx'
        title: Title shown on the opening slide
        slides: List of slide dicts, each with:
                - "title" (str): slide title
                - "bullets" (list[str]): bullet point lines
                - "notes" (str, optional): speaker notes
    """
    try:
        from pptx import Presentation

        prs = Presentation()

        title_slide = prs.slides.add_slide(prs.slide_layouts[0])
        title_slide.shapes.title.text = title
        subtitle = title_slide.placeholders.get(1)
        if subtitle:
            subtitle.text = "Generated by Karen"

        for slide_data in slides:
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = slide_data.get("title", "")

            bullets = slide_data.get("bullets", [])
            content_ph = slide.placeholders.get(1)
            if bullets and content_ph:
                tf = content_ph.text_frame
                tf.clear()
                for i, bullet in enumerate(bullets):
                    if i == 0:
                        tf.text = bullet
                    else:
                        tf.add_paragraph().text = bullet

            notes_text = slide_data.get("notes", "")
            if notes_text:
                slide.notes_slide.notes_text_frame.text = notes_text

        buf = io.BytesIO()
        prs.save(buf)
        location = storage.write_file(filename, buf.getvalue())
        return f"PowerPoint saved: {location} ({len(slides)} slides)"
    except Exception as e:
        return f"Error creating PowerPoint: {e}"
