version: 0.2

env:
  variables:
    VITE_AWS_REGION: "us-east-1"
  secrets-manager:
    VITE_COGNITO_USER_POOL_ID: "william/cognito:user_pool_id"
    VITE_COGNITO_CLIENT_ID: "william/cognito:client_id"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8)

  build:
    commands:
      - echo Building Docker image...
      - docker build --build-arg VITE_COGNITO_USER_POOL_ID=$VITE_COGNITO_USER_POOL_ID --build-arg VITE_COGNITO_CLIENT_ID=$VITE_COGNITO_CLIENT_ID --build-arg VITE_AWS_REGION=$VITE_AWS_REGION -t $IMAGE_URI:$IMAGE_TAG -t $IMAGE_URI:latest .

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $IMAGE_URI:$IMAGE_TAG
      - docker push $IMAGE_URI:latest
      - echo Writing image definitions for ECS...
      - printf '[{"name":"william","imageUri":"%s"}]' "$IMAGE_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
